import Document, {DocumentContext, DocumentInitialProps, Head, Html, Main, NextScript} from "next/document";

class MyDocument extends Document {
    static async getInitialProps(ctx: DocumentContext): Promise<DocumentInitialProps> {
        const initialProps = await Document.getInitialProps(ctx);
        return { ...initialProps };
    }

    render(): JSX.Element {
        return (
            <Html lang="ru">
                <Head>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
                  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;500;700&display=swap" />
                  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
                        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
                        crossOrigin="anonymous" />
                </Head>
                <body>
                  <Main />
                  <NextScript />
                </body>
            </Html>
        );
    }
}

export default MyDocument;